# Generated by Django 5.1.4 on 2024-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('health', 'Health')], max_length=50)),
                ('location', models.CharField(choices=[('new_york', 'New York'), ('los_angeles', 'Los Angeles'), ('chicago', 'Chicago'), ('san_francisco', 'San Francisco'), ('all_locations', 'All Locations')], default='all_locations', max_length=50)),
            ],
        ),
    ]
